📦 NEW: Add Donate link mrahmadawais & ahmadawais
feross/thanks pull request #41
Opened 2018-02-10 05:29 UTC by ahmadawais

This PR adds donate links for my packages

Thanks for creating this awesome tool.

2018-02-13 16:34 UTC, feross requested changes
Thanks for the PR. There are some issues you need to fix before I can merge this.

2018-02-13 16:34 UTC, feross commented on index.js
> +  ahmadawais: 'https://pay.paddle.com/checkout/515568',
This is not a valid npm user: https://www.npmjs.com/~ahmadawais

Please remove this line

2018-02-13 16:34 UTC, feross commented on index.js
> +  'babel-preset-cgb': 'https://pay.paddle.com/checkout/515568',
Please remove all the individual packages from this section. It's sufficient to add yourself to the `authors` object for all your packages to be detected.

2018-02-15 12:02 UTC, ahmadawais commented
@feross Sure, I just fixed all of that. Only the author and link names.

```js
mrahmadawais: 'https://pay.paddle.com/checkout/515568',
```

Looking forward!

2018-02-16 09:50 UTC, feross approved these changes

2018-02-16 09:50 UTC, merged

2018-02-16 09:51 UTC, feross commented
Thanks @ahmadawais!